### PR TITLE
Change-qos

### PR DESCRIPTION
**Pull request by tonynajjar**

### CODE REVIEW

**Comment by tonynajjar** [comment]
image

We unfortunately have to accept this warning. That's because I do not remap our camera_info topic for this node to use. If I did it would try to generate .ini that we don't need. And I say try because there even an error in doing this.

I don't see a way to disable camera_info from being used

**Comment by tonynajjar** [comment]
Well actually I could just remove the camera_info subscriber since we forked it but then we can submit a PR with it.

**Comment by tonynajjar** [comment]
Anyway we can't submit a PR that doesn't offer a way to override the QOS so for now I would make the changes that are useful for us. I'd remove the camera_info subscriber

**Review by jplapp — APPROVED** [review]
interesting, I thought that camera_info as anyway published at a lower rate, but seems like it should be in sync

**Pull request merged**
